// src/platform/packages/shared/shared-ux/page/kibana_no_data/impl/src/services.tsx
/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import type { FC, PropsWithChildren } from 'react';
import React, { useContext } from 'react';
import {
  NoDataViewsPromptProvider,
  NoDataViewsPromptKibanaProvider,
} from '@kbn/shared-ux-prompt-no-data-views';

import { NoDataCardProvider, NoDataCardKibanaProvider } from '@kbn/shared-ux-card-no-data';

import type {
  Services,
  KibanaNoDataPageServices,
  KibanaNoDataPageKibanaDependencies,
} from '@kbn/shared-ux-page-kibana-no-data-types';

const KibanaNoDataPageContext = React.createContext<Services | null>(null);

/**
 * A Context Provider that provides services to the component.
 */
export const KibanaNoDataPageProvider: FC<PropsWithChildren<KibanaNoDataPageServices>> = ({
  children,
  ...services
}) => {
  const { hasESData, hasUserDataView } = services;

  return (
    <KibanaNoDataPageContext.Provider value={{ hasESData, hasUserDataView }}>
      <NoDataViewsPromptProvider {...services}>
        <NoDataCardProvider {...services}>{children}</NoDataCardProvider>
      </NoDataViewsPromptProvider>
    </KibanaNoDataPageContext.Provider>
  );
};

/**
 * Kibana-specific Provider that maps dependencies to services.
 */
export const KibanaNoDataPageKibanaProvider: FC<
  PropsWithChildren<KibanaNoDataPageKibanaDependencies>
> = ({ children, ...dependencies }) => {
  const { dataViews } = dependencies;
  const value: Services = {
    hasESData: dataViews.hasData.hasESData,
    hasUserDataView: dataViews.hasData.hasUserDataView,
  };

  return (
    <KibanaNoDataPageContext.Provider value={value}>
      <NoDataViewsPromptKibanaProvider {...dependencies}>
        <NoDataCardKibanaProvider {...dependencies}>{children}</NoDataCardKibanaProvider>
      </NoDataViewsPromptKibanaProvider>
    </KibanaNoDataPageContext.Provider>
  );
};

/**
 * React hook for accessing pre-wired services.
 */
export function useServices() {
  const context = useContext(KibanaNoDataPageContext);

  if (!context) {
    throw new Error(
      'KibanaNoDataPageContext is missing.  Ensure your component or React root is wrapped with KibanaNoDataPageContext.'
    );
  }

  return context;
}

// packages/home/sample_data_card/src/services.tsx
/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import type { FC, PropsWithChildren, MouseEventHandler} from 'react';
import React, { useContext } from 'react';
import type { EuiGlobalToastListToast as EuiToast } from '@elastic/eui';

import { SAMPLE_DATA_API } from './constants';

type NavigateToUrl = (url: string) => Promise<void> | void;
type UnmountCallback = () => void;
type MountPoint<T extends HTMLElement = HTMLElement> = (element: T) => UnmountCallback;
type ValidNotifyString = string | MountPoint<HTMLElement>;

type NotifyInputFields = Pick<EuiToast, Exclude<keyof EuiToast, 'id' | 'text' | 'title'>> & {
  title?: ValidNotifyString;
  text?: ValidNotifyString;
};

type NotifyInput = string | NotifyInputFields;
type NotifyFn = (notification: NotifyInput) => void;

/**
 * A list of services that are consumed by this component.
 */
export interface Services {
  addBasePath: (path: string) => string;
  getAppNavigationHandler: (path: string) => MouseEventHandler;
  installSampleDataSet: (id: string, defaultIndex: string) => Promise<void>;
  notifyError: NotifyFn;
  notifySuccess: NotifyFn;
  removeSampleDataSet: (id: string, defaultIndex: string) => Promise<void>;
}

const Context = React.createContext<Services | null>(null);

/**
 * A Context Provider that provides services to the component and its dependencies.
 */
export const SampleDataCardProvider: FC<PropsWithChildren<Services>> = ({
  children,
  ...services
}) => {
  const {
    addBasePath,
    getAppNavigationHandler,
    installSampleDataSet,
    notifyError,
    notifySuccess,
    removeSampleDataSet,
  } = services;

  return (
    <Context.Provider
      value={{
        addBasePath,
        getAppNavigationHandler,
        installSampleDataSet,
        notifyError,
        notifySuccess,
        removeSampleDataSet,
      }}
    >
      {children}
    </Context.Provider>
  );
};

export interface KibanaDependencies {
  coreStart: {
    application: {
      navigateToUrl: NavigateToUrl;
    };
    http: {
      basePath: {
        prepend: (path: string) => string;
      };
      delete: (path: string) => Promise<unknown>;
      post: (path: string) => Promise<unknown>;
    };
    notifications: {
      toasts: {
        addDanger: NotifyFn;
        addSuccess: NotifyFn;
      };
    };
    uiSettings: {
      get: (key: string, defaultOverride?: any) => any;
      isDefault: (key: string) => boolean;
      set: (key: string, value: any) => Promise<boolean>;
    };
  };
  dataViews: {
    clearCache: () => void;
  };
}

/**
 * Kibana-specific Provider that maps dependencies to services.
 */
export const SampleDataCardKibanaProvider: FC<PropsWithChildren<KibanaDependencies>> = ({
  children,
  ...dependencies
}) => {
  const { application, http, notifications, uiSettings } = dependencies.coreStart;
  const clearDataViewsCache = dependencies.dataViews.clearCache;

  const value: Services = {
    addBasePath: http.basePath.prepend,
    getAppNavigationHandler: (targetUrl) => (event) => {
      if (event.altKey || event.metaKey || event.ctrlKey) {
        return;
      }
      event.preventDefault();
      application.navigateToUrl(http.basePath.prepend(targetUrl));
    },
    installSampleDataSet: async (id, defaultIndex) => {
      await http.post(`${SAMPLE_DATA_API}/${id}`);

      if (uiSettings.isDefault('defaultIndex')) {
        uiSettings.set('defaultIndex', defaultIndex);
      }

      clearDataViewsCache();
    },
    removeSampleDataSet: async (id, defaultIndex) => {
      await http.delete(`${SAMPLE_DATA_API}/${id}`);

      if (
        !uiSettings.isDefault('defaultIndex') &&
        uiSettings.get('defaultIndex') === defaultIndex
      ) {
        uiSettings.set('defaultIndex', null);
      }

      clearDataViewsCache();
    },
    notifyError: (input) => notifications.toasts.addDanger(input),
    notifySuccess: (input) => notifications.toasts.addSuccess(input),
  };

  return <Context.Provider {...{ value }}>{children}</Context.Provider>;
};

/**
 * React hook for accessing pre-wired services.
 */
export function useServices() {
  const context = useContext(Context);

  if (!context) {
    throw new Error(
      'SampleDataCard Context is missing.  Ensure your component or React root is wrapped with SampleDataCardContext.'
    );
  }

  return context;
}
